# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(800, 600)
        self.AnaForm = QtWidgets.QWidget(menu)
        self.AnaForm.setObjectName("AnaForm")
        self.tableWidget = QtWidgets.QTableWidget(self.AnaForm)
        self.tableWidget.setGeometry(QtCore.QRect(0, 11, 901, 591))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        menu.setCentralWidget(self.AnaForm)
        self.menubar = QtWidgets.QMenuBar(menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.kliste = QtWidgets.QMenu(self.menubar)
        self.kliste.setObjectName("kliste")
        self.kekle = QtWidgets.QMenu(self.menubar)
        self.kekle.setObjectName("kekle")
        self.kguncelle = QtWidgets.QMenu(self.menubar)
        self.kguncelle.setObjectName("kguncelle")
        self.ksil = QtWidgets.QMenu(self.menubar)
        self.ksil.setObjectName("ksil")
        self.cikis = QtWidgets.QMenu(self.menubar)
        self.cikis.setObjectName("cikis")
        menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menu)
        self.statusbar.setObjectName("statusbar")
        menu.setStatusBar(self.statusbar)
        self.actioneklemek = QtWidgets.QAction(menu)
        self.actioneklemek.setObjectName("actioneklemek")
        self.actionguncelle = QtWidgets.QAction(menu)
        self.actionguncelle.setObjectName("actionguncelle")
        self.actionsil = QtWidgets.QAction(menu)
        self.actionsil.setObjectName("actionsil")
        self.actioncikis = QtWidgets.QAction(menu)
        self.actioncikis.setObjectName("actioncikis")
        self.actionlistele = QtWidgets.QAction(menu)
        self.actionlistele.setObjectName("actionlistele")
        self.kliste.addAction(self.actionlistele)
        self.kekle.addAction(self.actioneklemek)
        self.kguncelle.addAction(self.actionguncelle)
        self.ksil.addSeparator()
        self.ksil.addAction(self.actionsil)
        self.cikis.addAction(self.actioncikis)
        self.menubar.addAction(self.kliste.menuAction())
        self.menubar.addAction(self.kekle.menuAction())
        self.menubar.addAction(self.kguncelle.menuAction())
        self.menubar.addAction(self.ksil.menuAction())
        self.menubar.addAction(self.cikis.menuAction())

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("menu", "kitap_id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("menu", "kitap adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("menu", "kitap yazarı"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("menu", "okunma durumu"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("menu", "beğeni durumu"))
        self.kliste.setTitle(_translate("menu", "Kitap Listesi"))
        self.kekle.setTitle(_translate("menu", "Kitap Ekle"))
        self.kguncelle.setTitle(_translate("menu", "Kitap Güncelle"))
        self.ksil.setTitle(_translate("menu", "Kitap Sil"))
        self.cikis.setTitle(_translate("menu", "Çıkış"))
        self.actioneklemek.setText(_translate("menu", "kitap ekle"))
        self.actionguncelle.setText(_translate("menu", "guncelle"))
        self.actionsil.setText(_translate("menu", "sil"))
        self.actioncikis.setText(_translate("menu", "cikis"))
        self.actionlistele.setText(_translate("menu", "listele"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu = QtWidgets.QMainWindow()
    ui = Ui_menu()
    ui.setupUi(menu)
    menu.show()
    sys.exit(app.exec_())
